name: Build and Test

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Lint the extension
        run: npm run lint

      - name: Build the extension
        run: npm run build

      - name: Test the extension
        run: npm run test

      - name: Package the extension
        run: npm run package

      - name: Save artifact to commit
        uses: actions/upload-artifact@v3
        with:
          name: prod.zip
          path: prod.zip
          if-no-files-found: error

